

----------

CREATE COLUMN TABLE "EMPLOYEE"(
   "EID" NVARCHAR(64) NOT NULL,
   "ENAME" NVARCHAR(255),
   "EDEPT" NVARCHAR(255) NOT NULL,
   PRIMARY KEY ("EID"));

CREATE INDEX "EID_EMPLOYEE" on "EMPLOYEE" ("EID");
